language: python
python:
  - "3.6"
before_install:
  - openssl aes-256-cbc -K $encrypted_6042638369ba_key -iv $encrypted_6042638369ba_iv -in tests/utils/gdrive/token.json.enc -out tests/utils/gdrive/token.json -d
  - openssl aes-256-cbc -K $encrypted_6042638369ba_key -iv $encrypted_6042638369ba_iv -in tests/utils/gdrive/credentials.json.enc -out tests/utils/gdrive/credentials.json -d
install:
  - pip install -r requirements.txt
script:
  - pytest --html=reports/report.html --self-contained-html
after_script:
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then TEST_MESSAGE="Tests passed -"; else TEST_MESSAGE="Tests failed -"; fi
  - TEST_REPORT_DOWNLOAD_URL=$(python tests/utils/gdrive/upload_test_report.py)
  - echo $TEST_REPORT_DOWNLOAD_URL
  - python tests/utils/gdrive/comment.py $GITHUB_KEY $TRAVIS_REPO_SLUG $TRAVIS_PULL_REQUEST "$TEST_MESSAGE $TEST_REPORT_DOWNLOAD_URL"
