language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest --html=reports/report.html
after_success:
  - echo "Tests passed - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
after_failure:
  - echo "Tests failed"
